import { QuestionScoring } from "../types/company.js";

export const questionScoringSeed: QuestionScoring[] = [
  {
    code: "1-1",
    priority: "LOW",
    requirement: "Minimum",
    maxPoints: 2.0,
  },
  {
    code: "1-6",
    priority: "LOW",
    requirement: "Minimum",
    maxPoints: 1.0,
  },
  {
    code: "1-2",
    priority: "LOW",
    requirement: "Minimum",
    maxPoints: 1.0,
  },
  {
    code: "1-3",
    priority: "LOW",
    requirement: null,
    maxPoints: 1.0,
  },
  {
    code: "1-4",
    priority: "LOW",
    requirement: null,
    maxPoints: 2.0,
  },
  {
    code: "1-7",
    priority: "MEDIUM",
    requirement: null,
    maxPoints: 2.0,
  },
  {
    code: "2-1-1",
    priority: "HIGH",
    requirement: "Minimum",
    maxPoints: 2.0,
  },
  {
    code: "2-1-2",
    priority: "HIGH",
    requirement: "Minimum",
    maxPoints: 1.0,
  },
  {
    code: "2-3",
    priority: "HIGH",
    requirement: "Minimum",
    maxPoints: 2.0,
  },
  {
    code: "2-4",
    priority: "HIGH",
    requirement: "Minimum",
    maxPoints: 2.0,
  },
  {
    code: "2-1-3",
    priority: "MEDIUM",
    requirement: "Minimum",
    maxPoints: 1.0,
  },
  {
    code: "2-2-1",
    priority: "MEDIUM",
    requirement: "Minimum",
    maxPoints: 1.0,
  },
  {
    code: "2-2-2",
    priority: "MEDIUM",
    requirement: null,
    maxPoints: 1.0,
  },
  {
    code: "2-5-1",
    priority: "HIGH",
    requirement: null,
    maxPoints: 2.0,
  },
  {
    code: "2-5-2",
    priority: "LOW",
    requirement: null,
    maxPoints: 1.0,
  },
  {
    code: "2-6",
    priority: "MEDIUM",
    requirement: null,
    maxPoints: 1.0,
  },
  {
    code: "3-1",
    priority: "MEDIUM",
    requirement: "Minimum",
    maxPoints: 2.0,
  },
  {
    code: "3-2",
    priority: "LOW",
    requirement: null,
    maxPoints: 2.0,
  },
  {
    code: "3-3",
    priority: "LOW",
    requirement: null,
    maxPoints: 1.0,
  },
  {
    code: "3-4",
    priority: "LOW",
    requirement: null,
    maxPoints: 1.0,
  },
  {
    code: "3-5",
    priority: "LOW",
    requirement: null,
    maxPoints: 3.0,
  },
  {
    code: "3-6",
    priority: "LOW",
    requirement: null,
    maxPoints: 2.0,
  },
  {
    code: "4-1",
    priority: "HIGH",
    requirement: "Minimum",
    maxPoints: 2.0,
  },
  {
    code: "4-4",
    priority: "MEDIUM",
    requirement: "Minimum",
    maxPoints: 1.0,
  },
  {
    code: "4-2",
    priority: "LOW",
    requirement: null,
    maxPoints: 2.0,
  },
  {
    code: "4-3",
    priority: "LOW",
    requirement: null,
    maxPoints: 1.0,
  },
  {
    code: "4-6",
    priority: "LOW",
    requirement: null,
    maxPoints: 1.0,
  },
  {
    code: "5-3",
    priority: "HIGH",
    requirement: "Minimum",
    maxPoints: 3.0,
  },
  {
    code: "5-1-1",
    priority: "HIGH",
    requirement: "Minimum",
    maxPoints: 6.0,
  },
  {
    code: "5-2",
    priority: "HIGH",
    requirement: "Minimum",
    maxPoints: 3.0,
  },
  {
    code: "5-5",
    priority: "HIGH",
    requirement: null,
    maxPoints: 2.0,
  },
  {
    code: "5-1-2",
    priority: "MEDIUM",
    requirement: null,
    maxPoints: 2.0,
  },
  {
    code: "5-4",
    priority: "MEDIUM",
    requirement: null,
    maxPoints: 4.0,
  },
  {
    code: "5-6",
    priority: "MEDIUM",
    requirement: null,
    maxPoints: 2.0,
  },
  {
    code: "5-7",
    priority: "LOW",
    requirement: null,
    maxPoints: 2.0,
  },
  {
    code: "8-1",
    priority: "MEDIUM",
    requirement: "Minimum",
    maxPoints: 2.0,
  },
  {
    code: "8-2",
    priority: "LOW",
    requirement: null,
    maxPoints: 1.0,
  },
  {
    code: "8-3",
    priority: "LOW",
    requirement: null,
    maxPoints: 1.0,
  },
  {
    code: "8-4",
    priority: "LOW",
    requirement: null,
    maxPoints: 3.0,
  },
  {
    code: "1-5",
    priority: "LOW",
    requirement: null,
    maxPoints: 1.0,
  },
  {
    code: "4-5",
    priority: "MEDIUM",
    requirement: "Minimum",
    maxPoints: 2.0,
  },
  {
    code: "6-1",
    priority: "HIGH",
    requirement: "Minimum",
    maxPoints: 6.0,
  },
  {
    code: "6-3",
    priority: "HIGH",
    requirement: "Minimum",
    maxPoints: 2.0,
  },
  {
    code: "6-2",
    priority: "LOW",
    requirement: null,
    maxPoints: 2.0,
  },
  {
    code: "6-4",
    priority: "HIGH",
    requirement: null,
    maxPoints: 2.0,
  },
  {
    code: "6-5",
    priority: "HIGH",
    requirement: null,
    maxPoints: 2.0,
  },
  {
    code: "6-6",
    priority: "HIGH",
    requirement: null,
    maxPoints: 2.0,
  },
  {
    code: "6-7",
    priority: "HIGH",
    requirement: null,
    maxPoints: 2.0,
  },
  {
    code: "7-1",
    priority: "HIGH",
    requirement: "Minimum",
    maxPoints: 4.0,
  },
  {
    code: "7-2",
    priority: "HIGH",
    requirement: "Minimum",
    maxPoints: 4.0,
  },
  {
    code: "7-4",
    priority: "HIGH",
    requirement: "Minimum",
    maxPoints: 1.0,
  },
  {
    code: "7-7",
    priority: "HIGH",
    requirement: "Minimum",
    maxPoints: 1.0,
  },
  {
    code: "7-3",
    priority: "MEDIUM",
    requirement: null,
    maxPoints: 2.0,
  },
  {
    code: "7-5",
    priority: "MEDIUM",
    requirement: null,
    maxPoints: 2.0,
  },
  {
    code: "7-6",
    priority: "MEDIUM",
    requirement: null,
    maxPoints: 1.0,
  },
];
