import { Question } from "../types/questions.js";

export type QuestionSeed = Question & {
  info?: string | null;
};

export const questionSeed: QuestionSeed[] = [
  {
    code: "1-1",
    categoryCode: "1",
    text: "Is your company committed to environmental and social sustainability in its supply chain?",
    choiceMode: "single",
    info: "Please, select one option.",
  },
  {
    code: "1-2",
    categoryCode: "1",
    text: "Do you have a sustainability report?",
    choiceMode: "single",
    info: "Please, select one option.",
  },
  {
    code: "1-3-1",
    categoryCode: "1",
    text: "Have you set factual or numeric targets for sustainability development?",
    choiceMode: "single",
    info: "Please, select one option.",
  },
  {
    code: "1-3-2",
    categoryCode: "1",
    text: "Are you interested in support in creating our science based sustainability targets (SBT´s)?",
    choiceMode: "single",
    info: null,
  },
  {
    code: "1-4",
    categoryCode: "1",
    text: "Are you engaged in collective action with your stakeholders to promote sustainability and find new solutions?",
    choiceMode: "multiple",
    info: "Please, select all that apply:",
  },
  {
    code: "1-7",
    categoryCode: "1",
    text: "How do you promote sustainable consumer behavior and a  sustainable lifestyle?",
    choiceMode: "single",
    info: "Educational campaigns might involve informing consumers on social media about the environmental impacts of the textile industry without attempting to sell anything or being directly linked to your products. Sustainability marketing campaigns entail regularly discussing sustainability as a part of your marketing efforts while being linked to your products or brand, or explicitly mentioning that you are a 'sustainable brand.' Choose all that apply. Educational social media content includes, for example, care instructions, sharing recycling and repair tips, disseminating global sustainability news and insights, and discussing challenges in the global textile industry. It does not focus on selling a product. Sustainability marketing campaigns are commercial content that focus on your brand's sustainability aspects.",
  },
  {
    code: "2-1-1",
    categoryCode: "1",
    text: "Does your brand disclose transparently in which country your products are manufactured and which country the materials are from?",
    choiceMode: "multiple",
    info: "Please, select all that apply:",
  },
  {
    code: "2-1-2",
    categoryCode: "1",
    text: "Is your tier 1 factory and manufacturer list publicly available on your website or online store?",
    choiceMode: "multiple",
    info: "Please, select all that apply:",
  },
  {
    code: "2-2-1",
    categoryCode: "1",
    text: "Please, provide a list of your tier 2 material suppliers including their location country:",
    choiceMode: "single",
    info: "Tier 2 factories and companies are your main material suppliers. They weave and knit the fabrics, treat leathers and so on. If you do not know which company or where the fabrics and materials you use in your products are made, please state this in the additional information field. Also specify, if you buy your materials from an importer, and that you are not in direct contact with the material manufacturer.",
  },
  {
    code: "2-2-2",
    categoryCode: "1",
    text: "Is your tier 2 materials supplier information publicly available on your website or online store?",
    choiceMode: "multiple",
    info: "Please, select all that apply:",
  },
  {
    code: "2-2-3",
    categoryCode: "1",
    text: "Tier 3-4: How far do you know your supply chain all the way to the raw material and fibre production?",
    choiceMode: "single",
    info: "Please, select one option:",
  },
  {
    code: "2-3",
    categoryCode: "1",
    text: "Do you have a supplier Code of Conduct?",
    choiceMode: "single",
    info: "Please, select one option:",
  },
  {
    code: "2-4-1",
    categoryCode: "1",
    text: "Do you have tier 1 for assembly or tier 2 materials production in so-called risk countries?",
    choiceMode: "single",
    info: "Provide additional information such as information on the audits and audit scores and assessments.",
  },
  {
    code: "2-4-2",
    categoryCode: "1",
    text: "Please list your tier 1 top production countries below.",
    choiceMode: "single",
    info: "Estimated amount (%) of how much of your tier 1 assembly (pcs, or €) is in this country.",
  },
  {
    code: "2-4-3",
    categoryCode: "1",
    text: "Please list your tier 2 top material manufacturing countries below.",
    choiceMode: "single",
    info: "Estimated amount (%) of how much of your tier 2 materials origin (pcs, or €) is in this country.",
  },
  {
    code: "2-5",
    categoryCode: "1",
    text: "How do you monitor and audit decent working conditions at your tier 1 suppliers?",
    choiceMode: "multiple",
    info: "Please, select all that apply. If you are excecuting several ways, for example depending on the product category, clarify how your audits are set up in the comment section.",
  },
  {
    code: "3-1",
    categoryCode: "1",
    text: "In what ways does your brand design products for long term use?",
    choiceMode: "single",
    info: "This may include, for example, product and material testing, high attention to fit and details, durable seams and prints, and product development based on customer feedback.",
  },
  {
    code: "3-2",
    categoryCode: "1",
    text: "How are your products designed for circularity (supporting easy repairability and recyclability)?",
    choiceMode: "multiple",
    info: "Please, select all that apply:",
  },
  {
    code: "3-3",
    categoryCode: "1",
    text: "How is the pre-consumer textile waste (e.g. cutting waste) from your production treated?",
    choiceMode: "multiple",
    info: "Please, select all that apply. Provide additional information, e.g. to whom it is donated.",
  },
  {
    code: "3-4-1",
    categoryCode: "1",
    text: "Are your items produced on-demand, by pre-order or made-to-order?",
    choiceMode: "multiple",
    info: "Please, select all that apply:",
  },
  {
    code: "3-4-2",
    categoryCode: "1",
    text: "How much of your collection (customer choices CC´s) are available as carry-overs or Never Out Of Stock (NOOS)?",
    choiceMode: "single",
    info: "Please, select one option:",
  },
  {
    code: "3-5",
    categoryCode: "1",
    text: "Select the circular services you are providing as a part of your business model:",
    choiceMode: "multiple",
    info: "Please, select all that apply. Service can also be provided by a third party.",
  },
  {
    code: "3-6",
    categoryCode: "1",
    text: "Do you use a digital product passport for your items?",
    choiceMode: "single",
    info: "Please, select one option. The EU Digital Product Passport (DPP) is a tool proposed by the European Commission (EC) to enhance transparency and promote circularity. It aims to share product information across the entire value chain, including data on raw material extraction, production, recycling, etc. The new draft regulation on DPP will likely impact the product information of most companies on their websites in the coming years.",
  },
  {
    code: "4-1",
    categoryCode: "1",
    text: "How do you deal with unsold inventory?",
    choiceMode: "single",
    info: "Please, select one option:",
  },
  {
    code: "4-2",
    categoryCode: "1",
    text: "How are your products packed for the delivery?",
    choiceMode: "multiple",
    info: "Please, select all that apply:",
  },
  {
    code: "4-4",
    categoryCode: "1",
    text: "Which of the following product information do you have visible for most of your products?",
    choiceMode: "single",
    info: "Please, add a link to an example product.",
  },
  {
    code: "4-5",
    categoryCode: "1",
    text: "Is your company donating a portion of the proceeds to a charitable organization or NGO?",
    choiceMode: "single",
    info: "Please, select one option:",
  },
  {
    code: "4-6",
    categoryCode: "1",
    text: "Have you opened the price structure of an example product?",
    choiceMode: "single",
    info: 'Choose "yes" in case you have explained the price break down of an example product publicly in your website. If you choose "Yes", provide a link to the source.',
  },
  {
    code: "4-7",
    categoryCode: "1",
    text: "What certificates or labels do your products have?",
    choiceMode: "single",
    info: "Labels and certificates that are marked on the product or mentioned in your online shop product descriptions or marketing (not including packaging and product labelling). Please also include certificates and labels that come from production facilities and materials.",
  },
  {
    code: "4-8",
    categoryCode: "1",
    text: "What sustainability claims and words do you use to describe your products or services?",
    choiceMode: "single",
    info: "Words and terms that are mentioned in your online shop product descriptions or marketing campaigns and social media referring to your products and business (including packaging & logistics).",
  },
  {
    code: "5-1-1",
    categoryCode: "2",
    text: "Select all of the following labour right principles (the ILO Declaration on Fundamental Principles and Rights at Work) that your brand is committed to and able to ensure alignment with at your tier 1 manufacturers:",
    choiceMode: "multiple",
    info: null,
  },
  {
    code: "5-1-2",
    categoryCode: "2",
    text: "How has your brand made sure that the ILO labour right principles are communicated to employees (tier 1).",
    choiceMode: "single",
    info: "e.g. If it is part of the contracts, translated to the local languages, or others. Please, select one:",
  },
  {
    code: "5-2-1",
    categoryCode: "2",
    text: "How much of your tier 1 manufacturers employees are paid?",
    choiceMode: "single",
    info: "Note: 'Living wage' is not the same as the local legal 'minimum wage'. 'Living wage' is the amount needed to cover workers' basic needs, including food, clothing, housing, healthcare, education, child care, transport, and savings.",
  },
  {
    code: "5-2-2",
    categoryCode: "2",
    text: "How are wages defined in your Code of Conduct?",
    choiceMode: "single",
    info: "Please, select one:",
  },
  {
    code: "5-3",
    categoryCode: "2",
    text: "How much of your tier 2 material manufacturers employees are paid?",
    choiceMode: "single",
    info: "Note: 'Living wage' is not the same as the local legal 'minimum wage'. 'Living wage' is the amount needed to cover workers' basic needs, including food, clothing, housing, healthcare, education, child care, transport, and savings.",
  },
  {
    code: "5-4",
    categoryCode: "2",
    text: "Which of the following steps are you taking to ensure decent working conditions in tier 2-4?",
    choiceMode: "single",
    info: null,
  },
  {
    code: "8-1",
    categoryCode: "2",
    text: "How does your brand support DEIB-issues: diversity, equity and inclusion?",
    choiceMode: "multiple",
    info: "Please, select all that apply:",
  },
  {
    code: "8-2",
    categoryCode: "2",
    text: "Is your design process focused on supporting body inclusivity?",
    choiceMode: "multiple",
    info: 'Please, select all that apply. Select "other" to provide more detailed information.',
  },
  {
    code: "8-3",
    categoryCode: "2",
    text: "Does your brand have a separate measurements table for customer body measurements?",
    choiceMode: "multiple",
    info: "Please, select all that apply:",
  },
  {
    code: "8-4",
    categoryCode: "2",
    text: "Do your product and brand pictures feature a variety of people?",
    choiceMode: "multiple",
    info: "Please, select all that apply:",
  },
  {
    code: "8-5-1",
    categoryCode: "2",
    text: "What is your clothing brands size range in customer body measurements you offer (cm) in womenwear and menswear?",
    choiceMode: "single",
    info: null,
  },
  {
    code: "8-6",
    categoryCode: "2",
    text: "What is your brands size range in footwear?",
    choiceMode: "single",
    info: null,
  },
  {
    code: "8-7",
    categoryCode: "2",
    text: "Does your brand have a clothing / shoe size conversion table on your website?",
    choiceMode: "multiple",
    info: "Please, select all that apply:",
  },
  {
    code: "8-8",
    categoryCode: "2",
    text: "Does your brand use AI enhanced or created campaign images or product images on your website or marketing?",
    choiceMode: "multiple",
    info: "Please, select all that apply:",
  },
  {
    code: "6-1-1",
    categoryCode: "3",
    text: "What kind of energy is used in your value chain?",
    choiceMode: "multiple",
    info: "Please, select all that apply:",
  },
  {
    code: "6-1-2",
    categoryCode: "3",
    text: "Are any parts of your production CO2-compensated?",
    choiceMode: "multiple",
    info: "Please, select all that apply:",
  },
  {
    code: "6-2",
    categoryCode: "3",
    text: "Is your company carbon footprint calculated?",
    choiceMode: "single",
    info: 'If you choose "No, but we are planning to", please provide additional information on the schedule and whether you are interested in finding suitable partners.',
  },
  {
    code: "6-3",
    categoryCode: "3",
    text: "Have you set clear numeric and factual sustainability targets?",
    choiceMode: "single",
    info: "Please, select one option:",
  },
  {
    code: "6-4",
    categoryCode: "3",
    text: "Are you familiar with EU Green Claims directive?",
    choiceMode: "single",
    info: "Please, select one option.",
  },
  {
    code: "6-5",
    categoryCode: "3",
    text: "How do you manage the water impact in your supply chain (Tier 2-4), water use and wastewater treatment?",
    choiceMode: "single",
    info: "If your brand has certificates, or is using certified materials, that include wastewater issues, like GOTS, you can include it here.",
  },
  {
    code: "6-6",
    categoryCode: "3",
    text: "Do you take action to manage the biodiversity impact of your operations?",
    choiceMode: "single",
    info: "Please, select one option:",
  },
  {
    code: "6-7",
    categoryCode: "3",
    text: "Have you calculated product-specific environmental footprints for your items?",
    choiceMode: "multiple",
    info: "Please, select all that apply:",
  },
  {
    code: "7-1-1",
    categoryCode: "3",
    text: "Does your brand have a materials and fibers policy?",
    choiceMode: "multiple",
    info: "Please, select all that apply:",
  },
  {
    code: "7-2",
    categoryCode: "3",
    text: "How have you minimized the use of hazardous chemicals in your value chain (tier 1-4 from assembly to fiber).",
    choiceMode: "single",
    info: "Please, choose from the following options considering the use of chemicals in your items:",
  },
  {
    code: "7-3",
    categoryCode: "3",
    text: "Have you implemented any of the following practices to decrease the use of chemicals in production?",
    choiceMode: "multiple",
    info: "Please, select all that apply:",
  },
  {
    code: "7-4",
    categoryCode: "3",
    text: "In case you use animal-based materials in your items, do you have an animal welfare policy?",
    choiceMode: "single",
    info: "Please, select one option:",
  },
  {
    code: "7-5-1",
    categoryCode: "3",
    text: "Do you use farmed fur (or other mentioned animal fibers) in any of your items?",
    choiceMode: "single",
    info: "Please, select one option:",
  },
  {
    code: "7-5-2",
    categoryCode: "3",
    text: "Do you use down or feathers in any of your items?",
    choiceMode: "single",
    info: "Please, select one option:",
  },
  {
    code: "7-5-3",
    categoryCode: "3",
    text: "Do you use genuine leather in any of your items?",
    choiceMode: "single",
    info: "Please, select one option:",
  },
  {
    code: "7-5-4",
    categoryCode: "3",
    text: "Do you use wool and other animal hair fibers in any of your items?",
    choiceMode: "single",
    info: "NOTE. These common animal hair fibers include lambswool, alpaca, mohair, angora. Please, select one option:",
  },
  {
    code: "7-6",
    categoryCode: "3",
    text: 'Are you able to trace down your animal based materials "all the way to the farm" (tier 4)?',
    choiceMode: "single",
    info: "Please, select one option:",
  },
  {
    code: "7-7",
    categoryCode: "3",
    text: "Is your lambswool mulesing-free?",
    choiceMode: "single",
    info: "Please, select one option:",
  },
  {
    code: "7-8",
    categoryCode: "3",
    text: "Are your products free from hormonal disruptors and other similar chemical treatments?",
    choiceMode: "single",
    info: "Common endocrine disruptors are Bisphenol A (BPA), Perchlorate, PFC and PFAS chemicals, Phthalates, flame retardants, lead, polybrominated diphenyl ethers ect. Our product contain or might contain the following substances:",
  },
];
