import { NewQuestionOption } from "../types/questions.js";

export const questionOptionsSeed: NewQuestionOption[] = [
  {
    questionCode: "1-1",
    text: "Yes, but it is not publicly communicated",
    additionalInfoType: "text",
    info: "If yes, please, provide more details about your brand sustainability commitments.",
  },
  {
    questionCode: "1-1",
    text: "Yes, it is publicly communicated",
    additionalInfoType: "text",
    info: "Additional information required",
  },
  {
    questionCode: "1-1",
    text: "No, we do not have a sustainability strategy or company commitments regarding sustainability",
    additionalInfoType: "url",
    info: "And a link where this information can be found on your website.",
  },
  {
    questionCode: "1-2",
    text: "We have a sustainability report",
    additionalInfoType: "url",
    info: "PASTE LINK HERE",
  },
  {
    questionCode: "1-2",
    text: "We have not done a sustainability report",
    additionalInfoType: "none",
  },
  {
    questionCode: "1-2",
    text: "We are interested in support in creating our\nsustainability report",
    additionalInfoType: "none",
  },
  {
    questionCode: "1-3-1",
    text: "Yes, and it is aligned with the UN Sustainable Development Goals (UN SDG´s)",
    additionalInfoType: "url",
    info: "Where are these targets communicated on your site? Please add link.",
  },
  {
    questionCode: "1-3-1",
    text: "Yes, we have targets and roadmap for sustainability. But it is not aligned with UN SDG´s.",
    additionalInfoType: "url",
    info: "PASTE LINK HERE",
  },
  {
    questionCode: "1-3-1",
    text: "No, we have not set any sustainability targets",
    additionalInfoType: "text",
    info: "If yes, please clarify what kind of factual and numeric sustainability targets your company has. Which UN SDG´s they align with?",
  },
  {
    questionCode: "1-3-2",
    text: "Yes",
    additionalInfoType: "none",
  },
  {
    questionCode: "1-3-2",
    text: "No",
    additionalInfoType: "none",
  },
  {
    questionCode: "1-4",
    text: "Yes, with multi-stakeholder initiatives (MSIs)",
    additionalInfoType: "text",
    info: "Multi-stakeholder initiatives (MSIs) are collaborations between businesses, civil society, and other stakeholders aimed at addressing issues of mutual concern, such as human rights and sustainability. Examples include the Forest Stewardship Council (FSC), the Better Cotton Initiative (BCI), and the Roundtable on Sustainable Palm Oil (RSPO).",
  },
  {
    questionCode: "1-4",
    text: "Yes, with non-governmental organisations (NGOs)",
    additionalInfoType: "text",
    info: "A non-governmental organization (NGO) is an organization that generally is formed independent from government. Please include work with charitable organizations as well.",
  },
  {
    questionCode: "1-4",
    text: "Yes, with academia",
    additionalInfoType: "text",
    info: "With academia we mean university and EU funded public projects, which results will benefit the general public when published.",
  },
  {
    questionCode: "1-4",
    text: "Yes, with other companies",
    additionalInfoType: "text",
    info: "Other companies include businesses that supply your brand with b2b-services regarding sustainability.",
  },
  {
    questionCode: "1-4",
    text: "No, we are not working with other stakeholders",
    additionalInfoType: "none",
  },
  {
    questionCode: "1-7",
    text: "Educational online content on your website and / or \nsocial media channels",
    additionalInfoType: "url",
    info: "LINK HERE",
  },
  {
    questionCode: "1-7",
    text: "Sustainability related Marketing Campaigns",
    additionalInfoType: "url",
    info: "LINK HERE",
  },
  {
    questionCode: "2-1-1",
    text: "Made in country is announced (tier 1 assembly) by product",
    additionalInfoType: "text",
    info: "Your comments / additional information:",
  },
  {
    questionCode: "2-1-1",
    text: "Material origin country is announced by product \n(tier 2 fabric and material manufacturer)",
    additionalInfoType: "none",
  },
  {
    questionCode: "2-1-1",
    text: "Threads and fiber origin announced (tier 3-4) by product",
    additionalInfoType: "none",
  },
  {
    questionCode: "2-1-1",
    text: "None of the above",
    additionalInfoType: "text",
    info: "What transparency tool or service are you using?",
  },
  {
    questionCode: "2-1-1",
    text: "We have a 3rd party product transparency tool on our site which shows the manufacturer and origin country",
    additionalInfoType: "text",
    info: "Additional information required",
  },
  {
    questionCode: "2-1-2",
    text: "Yes, as a detailed factory / manufacturer list",
    additionalInfoType: "url",
    info: "If yes, please provide URL to the tier 1 factory list on your website.",
  },
  {
    questionCode: "2-1-2",
    text: "Yes, we have not released a factory list, but we have shared some manufacturing locations info in our sustainability page or product pages",
    additionalInfoType: "url",
    info: "PASTE LINK HERE",
  },
  {
    questionCode: "2-1-2",
    text: "Yes, we have a 3rd party product transparency tool on our site",
    additionalInfoType: "text",
    info: "Your comments / additional information:",
  },
  {
    questionCode: "2-1-2",
    text: "No, we do not have our tier 1 assembly factory lists, manufacturing locations or made-in countries",
    additionalInfoType: "none",
  },
  {
    questionCode: "2-2-2",
    text: "Yes, we have shared general material origin information in our sustainability page",
    additionalInfoType: "url",
    info: "If yes, please provide URL to the material origin information on your website.",
  },
  {
    questionCode: "2-2-2",
    text: "Yes, we have a 3rd party product transparency tool on our site",
    additionalInfoType: "url",
    info: "PASTE LINK HERE",
  },
  {
    questionCode: "2-2-2",
    text: "Yes, we have published a detailed material supplier list on our website",
    additionalInfoType: "text",
    info: "Your comments / additional information:",
  },
  {
    questionCode: "2-2-2",
    text: "No, we do not share any tier 2 material supplier information",
    additionalInfoType: "none",
  },
  {
    questionCode: "2-2-3",
    text: "We know most of our materials up to tier 3, to threads production",
    additionalInfoType: "none",
  },
  {
    questionCode: "2-2-3",
    text: 'We know most of our materials up to tier 4 fiber production, "all the way to the farm / field"',
    additionalInfoType: "none",
  },
  {
    questionCode: "2-2-3",
    text: "Our material sourcing is done by a certificate, so we do not know the origin of threads and fibers",
    additionalInfoType: "none",
  },
  {
    questionCode: "2-2-3",
    text: "We do not know the origin of our threads or fibers",
    additionalInfoType: "none",
  },
  {
    questionCode: "2-3",
    text: "Yes, but it is not publicly available (email us a copy)",
    additionalInfoType: "url",
    info: "PASTE LINK HERE OR EMAIL US A COPY",
  },
  {
    questionCode: "2-3",
    text: "Yes, and it is publicly available",
    additionalInfoType: "text",
    info: "THIS INFORMATION WILL BE TREATED AS CONFIDENTIAL.",
  },
  {
    questionCode: "2-3",
    text: "No, we do not have a Code of Conduct",
    additionalInfoType: "text",
    info: 'If you replied "we do not need a CoC" please clarify why?',
  },
  {
    questionCode: "2-3",
    text: "We do not need a Code of Conduct",
    additionalInfoType: "text",
    info: "Additional information required",
  },
  {
    questionCode: "2-4-1",
    text: "We produce in risk countries",
    additionalInfoType: "url",
    info: "Risk counties include for example China, Bangladesh, Vietnam, Indonesia, Myammar, India, Pakistan and Turkey. \nFor more information about risk countries, please check https://www.amfori.org/sites/default/files/amfori-2020-11-12-Country-Risk-Classification-2021_0.pdf",
  },
  {
    questionCode: "2-4-1",
    text: "Some of our materials / fabrics come from risk countries, but we have no tier 1 production in them.",
    additionalInfoType: "none",
  },
  {
    questionCode: "2-4-1",
    text: "We don't have any tier 1 or tier 2 production in risk countries",
    additionalInfoType: "text",
    info: "Your comments / additional information:",
  },
  {
    questionCode: "2-4-2",
    text: "COUNTRY",
    additionalInfoType: "none",
  },
  {
    questionCode: "2-4-2",
    text: "IN TOTAL",
    additionalInfoType: "text",
    info: "THIS INFORMATION WILL BE TREATED AS CONFIDENTIAL.",
  },
  {
    questionCode: "2-4-3",
    text: "COUNTRY",
    additionalInfoType: "none",
  },
  {
    questionCode: "2-4-3",
    text: "IN TOTAL",
    additionalInfoType: "text",
    info: "THIS INFORMATION WILL BE TREATED AS CONFIDENTIAL.",
  },
  {
    questionCode: "2-5",
    text: "Yes, regular third-party auditing",
    additionalInfoType: "text",
    info: "If yes, please describe which organization does the auditing for you.",
  },
  {
    questionCode: "2-5",
    text: "Yes, regular visits by our own staff",
    additionalInfoType: "none",
  },
  {
    questionCode: "2-5",
    text: "We have no tier 1 audits",
    additionalInfoType: "text",
    info: "THIS INFORMATION WILL BE TREATED AS CONFIDENTIAL.",
  },
  {
    questionCode: "2-5",
    text: "We would like some guidance in this topic.",
    additionalInfoType: "none",
  },
  {
    questionCode: "3-1",
    text: "Quality fibers and material structures",
    additionalInfoType: "text",
    info: "Your comments / additional information:",
  },
  {
    questionCode: "3-1",
    text: "Timeless design & look",
    additionalInfoType: "none",
  },
  {
    questionCode: "3-1",
    text: "Quality seam structures and finishing",
    additionalInfoType: "none",
  },
  {
    questionCode: "3-1",
    text: "Material testing for durability (for example Martindale testing)",
    additionalInfoType: "none",
  },
  {
    questionCode: "3-1",
    text: "Unisex fits",
    additionalInfoType: "none",
  },
  {
    questionCode: "3-1",
    text: "None of the above",
    additionalInfoType: "none",
  },
  {
    questionCode: "3-2",
    text: "Design / product structure supports repairability",
    additionalInfoType: "text",
    info: "Your comments / additional information:",
  },
  {
    questionCode: "3-2",
    text: "Design structure supports customer body size changes",
    additionalInfoType: "none",
  },
  {
    questionCode: "3-2",
    text: "Spare parts with the product",
    additionalInfoType: "none",
  },
  {
    questionCode: "3-2",
    text: "Spare parts available on request",
    additionalInfoType: "none",
  },
  {
    questionCode: "3-2",
    text: "Design supports light modification and upgraidability",
    additionalInfoType: "none",
  },
  {
    questionCode: "3-2",
    text: "Use of mono-materials in the product",
    additionalInfoType: "none",
  },
  {
    questionCode: "3-2",
    text: "Laundry and care instructions on site or social media channels",
    additionalInfoType: "none",
  },
  {
    questionCode: "3-2",
    text: "Brand sells also clothing maintanance tools and detergents",
    additionalInfoType: "none",
  },
  {
    questionCode: "3-2",
    text: "Products have a high resale-value",
    additionalInfoType: "none",
  },
  {
    questionCode: "3-2",
    text: "None of the above",
    additionalInfoType: "none",
  },
  {
    questionCode: "3-3",
    text: "There is no textile waste from production (zero waste design)",
    additionalInfoType: "none",
  },
  {
    questionCode: "3-3",
    text: "It is upcycled into smaller items",
    additionalInfoType: "text",
    info: "It is recycled into new fibres? Please describe",
  },
  {
    questionCode: "3-3",
    text: "It is recycled into new fibres",
    additionalInfoType: "text",
    info: "Additional information required",
  },
  {
    questionCode: "3-3",
    text: "It is downcycled to be used by other industries",
    additionalInfoType: "text",
    info: "Downcycled to be used by other industries? Please describe",
  },
  {
    questionCode: "3-3",
    text: "It is donated",
    additionalInfoType: "text",
    info: "Additional information required",
  },
  {
    questionCode: "3-3",
    text: "It is landfilled or incinerated",
    additionalInfoType: "text",
    info: "Donated? Please describe",
  },
  {
    questionCode: "3-3",
    text: "We do not know how it is treated",
    additionalInfoType: "none",
  },
  {
    questionCode: "3-3",
    text: "This is not relevant to us.",
    additionalInfoType: "none",
  },
  {
    questionCode: "3-4-1",
    text: "Yes, some of them are on-demand (B2B + retail)",
    additionalInfoType: "text",
    info: "B2B on-demand production is made for retail channel.",
  },
  {
    questionCode: "3-4-1",
    text: "Yes, some of them are pre-order (B2C)",
    additionalInfoType: "text",
    info: "B2C pre-orders are specifically produced for the consumer only, not for retail.",
  },
  {
    questionCode: "3-4-1",
    text: "Yes, we have made-to-order (B2C)",
    additionalInfoType: "text",
    info: "Made to order products are usually ateljee made, and they are put into production individually after each order.",
  },
  {
    questionCode: "3-4-1",
    text: "None of the above",
    additionalInfoType: "none",
  },
  {
    questionCode: "3-4-2",
    text: "Over 10% of our collection is carry overs or NOOS",
    additionalInfoType: "text",
    info: "CARRY OVER: An item in a line or collection that is carried over from one season to the next. These are styles that retailers can replenish throughout the season.\n\nThe NOOS model is centered on maintaining a continual supply of popular products and year-round staples, ensuring customers are not left frustrated by goods being out of stock.",
  },
  {
    questionCode: "3-4-2",
    text: "Over 30% of our collection is carry overs or NOOS",
    additionalInfoType: "none",
  },
  {
    questionCode: "3-4-2",
    text: "Over 50% of our collection is carry overs or NOOS",
    additionalInfoType: "none",
  },
  {
    questionCode: "3-4-2",
    text: "None of the above",
    additionalInfoType: "none",
  },
  {
    questionCode: "3-5",
    text: "Repair or maintenance service",
    additionalInfoType: "text",
    info: "Repair services can be provided in-house or by an outside service provider. Alternatively, the company can supply customers with spare parts.",
  },
  {
    questionCode: "3-5",
    text: "Take-back service",
    additionalInfoType: "text",
    info: "Take-back services mean that your brand buys back products from your customers. This servce can be provided by an outside partner.",
  },
  {
    questionCode: "3-5",
    text: "Selling second-hand items",
    additionalInfoType: "text",
    info: "Selling second hand items can be done through brand´s own site, or second hand selling service can be provided by an outside partner.",
  },
  {
    questionCode: "3-5",
    text: "Rental or leasing service",
    additionalInfoType: "none",
  },
  {
    questionCode: "3-5",
    text: "Extended product guarantee",
    additionalInfoType: "text",
    info: "Extended guarantees are lifetime guarantees and other product guarantees that are significally longer than the legal consumer protection time in your country.",
  },
  {
    questionCode: "3-5",
    text: "Other circular services",
    additionalInfoType: "text",
    info: "Additional information required",
  },
  {
    questionCode: "3-5",
    text: "No. We do not have any circular services.",
    additionalInfoType: "none",
  },
  {
    questionCode: "3-6",
    text: "Yes, our internal digital solution",
    additionalInfoType: "text",
    info: "If yes, please provide name of the service you have.",
  },
  {
    questionCode: "3-6",
    text: "Yes, digital solution provided by an external partner",
    additionalInfoType: "text",
    info: "Additional information required",
  },
  {
    questionCode: "3-6",
    text: "Yes we have a partner selected  for this, but have not published this fuction yet",
    additionalInfoType: "none",
  },
  {
    questionCode: "3-6",
    text: "This is not relevant to us",
    additionalInfoType: "text",
    info: "Your comments / additional information:",
  },
  {
    questionCode: "3-6",
    text: "We don´t know what EU Digital Product Passport is",
    additionalInfoType: "none",
  },
  {
    questionCode: "3-6",
    text: "We would like to have guidance on EU Digital Product Passport",
    additionalInfoType: "none",
  },
  {
    questionCode: "4-1",
    text: "We don't have any unsold inventory",
    additionalInfoType: "text",
    info: "If you don´t have any unsold inventory, please specify how.",
  },
  {
    questionCode: "4-1",
    text: "We resell only inside EU",
    additionalInfoType: "none",
  },
  {
    questionCode: "4-1",
    text: "We resell outside EU",
    additionalInfoType: "text",
    info: "THIS INFORMATION WILL BE TREATED AS CONFIDENTIAL.",
  },
  {
    questionCode: "4-2",
    text: "Certified cardboard / paper (for exampple FSC)",
    additionalInfoType: "text",
    info: "SELITYKSET TÄHÄN",
  },
  {
    questionCode: "4-2",
    text: "Recycled paper / cardboard",
    additionalInfoType: "none",
  },
  {
    questionCode: "4-2",
    text: "Biobased plastic / bio-plastics",
    additionalInfoType: "none",
  },
  {
    questionCode: "4-2",
    text: "Biodegradable plastic",
    additionalInfoType: "none",
  },
  {
    questionCode: "4-2",
    text: "Plastic packaging, including PE, PP and PET",
    additionalInfoType: "none",
  },
  {
    questionCode: "4-2",
    text: "Recycled plastic",
    additionalInfoType: "none",
  },
  {
    questionCode: "4-2",
    text: "Reusable packaging (for example RePack)",
    additionalInfoType: "url",
    info: "See more about this service at: https://www.repack.com/",
  },
  {
    questionCode: "4-2",
    text: "None of the above",
    additionalInfoType: "none",
  },
  {
    questionCode: "4-4",
    text: "Fiber content information by % and with official textilefiber names",
    additionalInfoType: "url",
    info: "Provide URL to an example product 1 on your online shop:",
  },
  {
    questionCode: "4-4",
    text: "Made in country / manufacturing country",
    additionalInfoType: "url",
    info: "LINK HERE",
  },
  {
    questionCode: "4-4",
    text: "Material origin country",
    additionalInfoType: "url",
    info: "Provide URL to an example product 2 on your online shop:",
  },
  {
    questionCode: "4-4",
    text: "Care instructions",
    additionalInfoType: "url",
    info: "LINK HERE",
  },
  {
    questionCode: "4-4",
    text: "Key measurements of product",
    additionalInfoType: "none",
  },
  {
    questionCode: "4-4",
    text: "Product measurements in different sizes",
    additionalInfoType: "none",
  },
  {
    questionCode: "4-4",
    text: "Customer body measurements table",
    additionalInfoType: "none",
  },
  {
    questionCode: "4-4",
    text: "Product images from several angles and details",
    additionalInfoType: "none",
  },
  {
    questionCode: "4-4",
    text: "Product images on different sized customers",
    additionalInfoType: "none",
  },
  {
    questionCode: "4-4",
    text: "We would like to have guidance on better product information",
    additionalInfoType: "none",
  },
  {
    questionCode: "4-5",
    text: "We are not doing this.",
    additionalInfoType: "none",
  },
  {
    questionCode: "4-5",
    text: "Yes, we are donating a portion of sales to charity as a continuous action",
    additionalInfoType: "url",
    info: "If yes, please provide URL of where this collaboration is explained on your site.  What organization are you working with?",
  },
  {
    questionCode: "4-5",
    text: "Yes, we are donating a portion of sales to charity as a temporary campaign",
    additionalInfoType: "text",
    info: "Additional information required",
  },
  {
    questionCode: "4-5",
    text: "Yes, we have done this in the past, but not anymore",
    additionalInfoType: "text",
    info: "Additional information required",
  },
  {
    questionCode: "4-6",
    text: "Yes",
    additionalInfoType: "url",
    info: "If yes, please provide URL of where this is explained on your site or social media.",
  },
  {
    questionCode: "4-6",
    text: "No",
    additionalInfoType: "url",
    info: "LINK HERE",
  },
  {
    questionCode: "4-7",
    text: "WE DO NOT HAVE ANY CERTIFICATES OR LABELS",
    additionalInfoType: "text",
    info: "If you have chose NOT to have any certificates and labels for your business, please explain why.",
  },
  {
    questionCode: "4-7",
    text: "Global Organic Textile Standard (GOTS)",
    additionalInfoType: "none",
  },
  {
    questionCode: "4-7",
    text: "Better Cotton Initiative (BCI)",
    additionalInfoType: "none",
  },
  {
    questionCode: "4-7",
    text: "Global Recycle Standard (GRS)",
    additionalInfoType: "none",
  },
  {
    questionCode: "4-7",
    text: "Organic Content Standard (OCS)",
    additionalInfoType: "none",
  },
  {
    questionCode: "4-7",
    text: "Forest Stewardship Council (FSC)",
    additionalInfoType: "none",
  },
  {
    questionCode: "4-7",
    text: "Responsible Wool Standard (RWS)",
    additionalInfoType: "none",
  },
  {
    questionCode: "4-7",
    text: "Responsible Down Standard (RDS)",
    additionalInfoType: "text",
    info: "If other, please list which certificates and labels.",
  },
  {
    questionCode: "4-7",
    text: "Responsible Alpaca Standard (RAS)",
    additionalInfoType: "none",
  },
  {
    questionCode: "4-7",
    text: "Responsible Mohair Standard (RMS)",
    additionalInfoType: "none",
  },
  {
    questionCode: "4-7",
    text: "OEKO-TEX® STANDARD 100",
    additionalInfoType: "none",
  },
  {
    questionCode: "4-7",
    text: "EU ECOLABEL",
    additionalInfoType: "none",
  },
  {
    questionCode: "4-7",
    text: "Worldwide Responsible Accredited Production (WRAP)",
    additionalInfoType: "none",
  },
  {
    questionCode: "4-7",
    text: "BlueSign",
    additionalInfoType: "none",
  },
  {
    questionCode: "4-7",
    text: "Fairtrade",
    additionalInfoType: "none",
  },
  {
    questionCode: "4-7",
    text: "The Vegan Society Trademark",
    additionalInfoType: "none",
  },
  {
    questionCode: "4-7",
    text: "PETA Approved Vegan",
    additionalInfoType: "none",
  },
  {
    questionCode: "4-7",
    text: "Nordic Swan Ecolabel / Joutsenmerkki",
    additionalInfoType: "none",
  },
  {
    questionCode: "4-7",
    text: "Avainlippu (FIN)",
    additionalInfoType: "none",
  },
  {
    questionCode: "4-7",
    text: "SA8000",
    additionalInfoType: "none",
  },
  {
    questionCode: "4-7",
    text: "B-CORP",
    additionalInfoType: "text",
    info: "Others might include:",
  },
  {
    questionCode: "4-7",
    text: "Sustainable Apparel Coalition (SAC)",
    additionalInfoType: "text",
    info: "The Global Biodiversity Standard (TGBS)",
  },
  {
    questionCode: "4-7",
    text: "Leather Working Group",
    additionalInfoType: "none",
  },
  {
    questionCode: "4-7",
    text: "Cradle to Cradle (C2C) Certification",
    additionalInfoType: "none",
  },
  {
    questionCode: "4-7",
    text: "ECOCERT Certification",
    additionalInfoType: "none",
  },
  {
    questionCode: "4-7",
    text: "Global Biodiversity Framework (GBF)",
    additionalInfoType: "none",
  },
  {
    questionCode: "4-7",
    text: "OEKO-TEX MADE IN GREEN",
    additionalInfoType: "none",
  },
  {
    questionCode: "4-7",
    text: "Other",
    additionalInfoType: "text",
    info: "Additional information required",
  },
  {
    questionCode: "4-8",
    text: "biodegradable / compostable",
    additionalInfoType: "text",
    info: "If other, please list which sustainability claims are used.",
  },
  {
    questionCode: "4-8",
    text: "environmentally friendly / planet-friendly / \neco-friendly / ecological",
    additionalInfoType: "none",
  },
  {
    questionCode: "4-8",
    text: "carbon neutral / carbon negative",
    additionalInfoType: "none",
  },
  {
    questionCode: "4-8",
    text: "recycled",
    additionalInfoType: "none",
  },
  {
    questionCode: "4-8",
    text: "organic",
    additionalInfoType: "none",
  },
  {
    questionCode: "4-8",
    text: "natural",
    additionalInfoType: "none",
  },
  {
    questionCode: "4-8",
    text: "vegan (in general)",
    additionalInfoType: "none",
  },
  {
    questionCode: "4-8",
    text: "vegan leather / pleather",
    additionalInfoType: "none",
  },
  {
    questionCode: "4-8",
    text: "hypoallergenic / antimicrobial / antibacterial",
    additionalInfoType: "none",
  },
  {
    questionCode: "4-8",
    text: "limited edition / small production",
    additionalInfoType: "none",
  },
  {
    questionCode: "4-8",
    text: "local production / locally produced",
    additionalInfoType: "none",
  },
  {
    questionCode: "4-8",
    text: "handmade",
    additionalInfoType: "none",
  },
  {
    questionCode: "4-8",
    text: "artisan",
    additionalInfoType: "none",
  },
  {
    questionCode: "4-8",
    text: "UV-protective / SPF",
    additionalInfoType: "none",
  },
  {
    questionCode: "4-8",
    text: "Other",
    additionalInfoType: "text",
    info: "Additional information required",
  },
  {
    questionCode: "5-1-1",
    text: "Freedom of association and the right to collective bargaining",
    additionalInfoType: "none",
  },
  {
    questionCode: "5-1-1",
    text: "No forced or compulsory labour",
    additionalInfoType: "none",
  },
  {
    questionCode: "5-1-1",
    text: "No child labour",
    additionalInfoType: "none",
  },
  {
    questionCode: "5-1-1",
    text: "No discrimination",
    additionalInfoType: "none",
  },
  {
    questionCode: "5-1-1",
    text: "A safe and healthy working environment",
    additionalInfoType: "none",
  },
  {
    questionCode: "5-1-1",
    text: "Decent hours of work",
    additionalInfoType: "none",
  },
  {
    questionCode: "5-1-1",
    text: "All of the above are a part of our Code of Conduct",
    additionalInfoType: "none",
  },
  {
    questionCode: "5-1-1",
    text: "Leave unchecked, if brand does not have a Code of Conduct.",
    additionalInfoType: "none",
  },
  {
    questionCode: "5-1-2",
    text: "All our tier 1 factories are audited by a third party.",
    additionalInfoType: "text",
    info: "Additional information required",
  },
  {
    questionCode: "5-1-2",
    text: "Our own staff has visited the factories, and reviewd all employee rights documents and contracts.",
    additionalInfoType: "none",
  },
  {
    questionCode: "5-1-2",
    text: "We assume it is a part of their contracts.",
    additionalInfoType: "none",
  },
  {
    questionCode: "5-1-2",
    text: "Labour rights are covered by a certificate (for example GOTS)",
    additionalInfoType: "none",
  },
  {
    questionCode: "5-1-2",
    text: "We don´t know.",
    additionalInfoType: "none",
  },
  {
    questionCode: "5-2-1",
    text: "100% employees at tier 1 are paid only the local minimum wage (much less than living wage)",
    additionalInfoType: "none",
  },
  {
    questionCode: "5-2-1",
    text: "Under 50% of the employees at all tier 1 manufacturers are paid a living wage",
    additionalInfoType: "none",
  },
  {
    questionCode: "5-2-1",
    text: "Over 50% of the employees at all tier 1 manufacturers are paid a living wage",
    additionalInfoType: "none",
  },
  {
    questionCode: "5-2-1",
    text: "100% of the employees at all tier 1 manufacturers are paid a living wage",
    additionalInfoType: "none",
  },
  {
    questionCode: "5-2-1",
    text: "We don´t know",
    additionalInfoType: "none",
  },
  {
    questionCode: "5-2-2",
    text: "Our Code of Conduct states manufacturers should pay local minimum wages",
    additionalInfoType: "none",
  },
  {
    questionCode: "5-2-2",
    text: "Our Code of Conduct states manufacturers should pay living wages",
    additionalInfoType: "none",
  },
  {
    questionCode: "5-2-2",
    text: "Wage are specified in our Code of Conduct by country",
    additionalInfoType: "none",
  },
  {
    questionCode: "5-2-2",
    text: "Our Code of Conduct does not specify wages",
    additionalInfoType: "none",
  },
  {
    questionCode: "5-2-2",
    text: "We do not have a Code of Conduct",
    additionalInfoType: "none",
  },
  {
    questionCode: "5-2-2",
    text: "We do not need a Code of Conduct",
    additionalInfoType: "none",
  },
  {
    questionCode: "5-2-2",
    text: "THIS INFORMATION WILL BE TREATED AS CONFIDENTIAL.",
    additionalInfoType: "none",
  },
  {
    questionCode: "5-3",
    text: "100% employees at tier 2 are paid only the local minimum wage (much less than living wage)",
    additionalInfoType: "none",
  },
  {
    questionCode: "5-3",
    text: "Under 50% of the employees at all tier 2 manufacturers are paid a living wage",
    additionalInfoType: "none",
  },
  {
    questionCode: "5-3",
    text: "Over 50% of the employees at all tier 2 manufacturers are paid a living wage",
    additionalInfoType: "none",
  },
  {
    questionCode: "5-3",
    text: "100% of the employees at all tier 2 manufacturers are paid a living wage",
    additionalInfoType: "none",
  },
  {
    questionCode: "5-3",
    text: "We have not examined wages, but our certificates cover also living wages at tier 2",
    additionalInfoType: "none",
  },
  {
    questionCode: "5-3",
    text: "We don´t know",
    additionalInfoType: "none",
  },
  {
    questionCode: "5-4",
    text: "Over 50% of used raw materials have certifications with social criteria (e.g. Fairtrade, GOTS)",
    additionalInfoType: "none",
  },
  {
    questionCode: "5-4",
    text: "Over 50% of raw materials and fibeers are manufactured in low risk countries",
    additionalInfoType: "none",
  },
  {
    questionCode: "5-4",
    text: "We visit and audit raw material production ourselves",
    additionalInfoType: "none",
  },
  {
    questionCode: "5-4",
    text: "We have close relationships with the raw material producers and audit their operations",
    additionalInfoType: "none",
  },
  {
    questionCode: "5-4",
    text: "THIS INFORMATION WILL BE TREATED AS CONFIDENTIAL.",
    additionalInfoType: "none",
  },
  {
    questionCode: "8-1",
    text: "We have a diverse work community / staff",
    additionalInfoType: "none",
  },
  {
    questionCode: "8-1",
    text: "We are doing marketing campaigns around inclusion and DEI-topics",
    additionalInfoType: "none",
  },
  {
    questionCode: "8-1",
    text: "We are designing our collections to be inclusive",
    additionalInfoType: "none",
  },
  {
    questionCode: "8-1",
    text: "We have examined diversity in our customer base",
    additionalInfoType: "none",
  },
  {
    questionCode: "8-1",
    text: "We have a company strategy for diversity, equity and inclusion",
    additionalInfoType: "none",
  },
  {
    questionCode: "8-1",
    text: "We have tested our online shop and collection with different customer groups (for example non-binary, plus sized people, people of color, people with disabilities)",
    additionalInfoType: "none",
  },
  {
    questionCode: "8-1",
    text: "DEI-topics are mentioned in our Code of Conduct",
    additionalInfoType: "none",
  },
  {
    questionCode: "8-1",
    text: "We are donating to organizations and campaigns supporting DEI-topics, like for example Women & Non-Binary run businesses",
    additionalInfoType: "none",
  },
  {
    questionCode: "8-1",
    text: "No, this has not been a focus area for us",
    additionalInfoType: "none",
  },
  {
    questionCode: "8-2",
    text: "Yes, through inclusive sizing",
    additionalInfoType: "text",
    info: "Describe how you support body and size inclusivity:",
  },
  {
    questionCode: "8-2",
    text: "Yes, through styling tips",
    additionalInfoType: "none",
  },
  {
    questionCode: "8-2",
    text: "Yes, through gender neutral pattern design",
    additionalInfoType: "none",
  },
  {
    questionCode: "8-2",
    text: "Yes, through gender neutral fit",
    additionalInfoType: "none",
  },
  {
    questionCode: "8-2",
    text: "Yes, for different body shapes (A, X, H O, Y)",
    additionalInfoType: "none",
  },
  {
    questionCode: "8-2",
    text: "Yes, for different body types (petite, curvy, tall)",
    additionalInfoType: "none",
  },
  {
    questionCode: "8-2",
    text: "Yes, through adaptive wear",
    additionalInfoType: "none",
  },
  {
    questionCode: "8-2",
    text: "No, this has not been our area of focus",
    additionalInfoType: "none",
  },
  {
    questionCode: "8-2",
    text: "Other",
    additionalInfoType: "text",
    info: "Additional information required",
  },
  {
    questionCode: "8-3",
    text: "No, we do not have a customer body measurement table, even though we sell products with sizes",
    additionalInfoType: "url",
    info: "Please provide URL to your customer body measurement size chart, if you have one on your website.",
  },
  {
    questionCode: "8-3",
    text: "Yes, we do, for clothes",
    additionalInfoType: "url",
    info: "LINK HERE",
  },
  {
    questionCode: "8-3",
    text: "Yes, we do, for underwear",
    additionalInfoType: "text",
    info: "Additional information required",
  },
  {
    questionCode: "8-3",
    text: "Yes, we do, for shoes",
    additionalInfoType: "text",
    info: "Your comments / additional information:",
  },
  {
    questionCode: "8-3",
    text: "Yes, we do, for other product categories",
    additionalInfoType: "text",
    info: "Additional information required",
  },
  {
    questionCode: "8-3",
    text: "We do not manufacture products with sizes",
    additionalInfoType: "none",
  },
  {
    questionCode: "8-4",
    text: "Yes, different sized people",
    additionalInfoType: "url",
    info: "Please provide URL to an example of diverse product pictures on your website.",
  },
  {
    questionCode: "8-4",
    text: "Yes, people of different ethnicities",
    additionalInfoType: "url",
    info: "LINK HERE",
  },
  {
    questionCode: "8-4",
    text: "Yes, people of different ages",
    additionalInfoType: "none",
  },
  {
    questionCode: "8-4",
    text: "Yes, people with disabilities",
    additionalInfoType: "none",
  },
  {
    questionCode: "8-4",
    text: "None of the above",
    additionalInfoType: "none",
  },
  {
    questionCode: "8-5-1",
    text: "We do not know our womenswear sizing in body cm",
    additionalInfoType: "none",
  },
  {
    questionCode: "8-5-1",
    text: "Our brand does not make clothing for women",
    additionalInfoType: "none",
  },
  {
    questionCode: "8-5-1",
    text: "We do not know our menswear sizing in body cm",
    additionalInfoType: "none",
  },
  {
    questionCode: "8-5-1",
    text: "Our brand does not make clothing for men",
    additionalInfoType: "none",
  },
  {
    questionCode: "8-6",
    text: "Our brand does not make footwear",
    additionalInfoType: "none",
  },
  {
    questionCode: "8-7",
    text: "Yes, for womenswear",
    additionalInfoType: "text",
    info: "What sizing systems are on your conversion table? \nEurope, UK, USA, Spain, Portugal, Australia, Japan, Mexico?",
  },
  {
    questionCode: "8-7",
    text: "Yes, for menswear",
    additionalInfoType: "text",
    info: "Additional information required",
  },
  {
    questionCode: "8-7",
    text: "Yes, for womens shoes",
    additionalInfoType: "text",
    info: "Additional information required",
  },
  {
    questionCode: "8-7",
    text: "Yes, for mens shoes",
    additionalInfoType: "text",
    info: "Additional information required",
  },
  {
    questionCode: "8-7",
    text: "None of the above",
    additionalInfoType: "url",
    info: "If yes, please add link to your size conversion page:",
  },
  {
    questionCode: "8-7",
    text: "We do not manufacture products with sizes",
    additionalInfoType: "url",
    info: "LINK HERE",
  },
  {
    questionCode: "8-7",
    text: "We don´t know",
    additionalInfoType: "none",
  },
  {
    questionCode: "8-8",
    text: "Yes, we do. And they have been marked as AI enhanced images.",
    additionalInfoType: "none",
  },
  {
    questionCode: "8-8",
    text: "Yes, we do. But they have not been marked as such.",
    additionalInfoType: "none",
  },
  {
    questionCode: "8-8",
    text: "No, we don´t.",
    additionalInfoType: "none",
  },
  {
    questionCode: "8-8",
    text: "I don´t know.",
    additionalInfoType: "none",
  },
  {
    questionCode: "6-1-1",
    text: "Over 50% of our product assembly (Tier 1) uses renewable energy",
    additionalInfoType: "text",
    info: "If other, please describe",
  },
  {
    questionCode: "6-1-1",
    text: "Over 50% of our material production (Tier 2) uses renewable energy",
    additionalInfoType: "none",
  },
  {
    questionCode: "6-1-1",
    text: "Over 50% of our threads manufacturers (Tier 3) use renewable energy",
    additionalInfoType: "none",
  },
  {
    questionCode: "6-1-1",
    text: "Over 50% of our fiber manufacturers (Tier 4) use renewable energy",
    additionalInfoType: "none",
  },
  {
    questionCode: "6-1-1",
    text: "Other, please describe",
    additionalInfoType: "text",
    info: "Additional information required",
  },
  {
    questionCode: "6-1-1",
    text: "We do not know what energy is used to make our products",
    additionalInfoType: "none",
  },
  {
    questionCode: "6-1-2",
    text: "Scope 1",
    additionalInfoType: "text",
    info: "What compensation service do you use?",
  },
  {
    questionCode: "6-1-2",
    text: "Scope 2",
    additionalInfoType: "text",
    info: "Additional information required",
  },
  {
    questionCode: "6-1-2",
    text: "Scope 3",
    additionalInfoType: "text",
    info: "Additional information required",
  },
  {
    questionCode: "6-1-2",
    text: "Only logistic (air freight, land freight, ocean freight...)",
    additionalInfoType: "text",
    info: "If other, please describe.",
  },
  {
    questionCode: "6-1-2",
    text: "Other, please describe",
    additionalInfoType: "text",
    info: "Additional information required",
  },
  {
    questionCode: "6-1-2",
    text: "We don´t know",
    additionalInfoType: "none",
  },
  {
    questionCode: "6-2",
    text: "Yes, for Scope 1 & 2",
    additionalInfoType: "text",
    info: "THIS INFORMATION WILL BE TREATED AS CONFIDENTIAL.",
  },
  {
    questionCode: "6-2",
    text: "Yes, for some categories of Scope 3",
    additionalInfoType: "text",
    info: 'If you choose "No, but we are planning to", please, describe',
  },
  {
    questionCode: "6-2",
    text: "Yes, for all significant categories of Scope 3",
    additionalInfoType: "none",
  },
  {
    questionCode: "6-2",
    text: "No",
    additionalInfoType: "none",
  },
  {
    questionCode: "6-2",
    text: "No, but we are planning to",
    additionalInfoType: "text",
    info: "Additional information required",
  },
  {
    questionCode: "6-3",
    text: "Yes, and they are science based targets (SBT´s)",
    additionalInfoType: "text",
    info: "If yes, describe your targets",
  },
  {
    questionCode: "6-3",
    text: "Yes, we have factual sustainability targets",
    additionalInfoType: "text",
    info: "Additional information required",
  },
  {
    questionCode: "6-3",
    text: "No, we do not have any factual targets",
    additionalInfoType: "none",
  },
  {
    questionCode: "6-3",
    text: "No, but we are planning to and interested in support",
    additionalInfoType: "text",
    info: "THIS INFORMATION WILL BE TREATED AS CONFIDENTIAL.",
  },
  {
    questionCode: "6-4",
    text: "Yes, we have a ecommerce strategy for Green Claims",
    additionalInfoType: "text",
    info: "Your comments / additional information:",
  },
  {
    questionCode: "6-4",
    text: "Yes, we have a marketing strategy for Green Claims",
    additionalInfoType: "none",
  },
  {
    questionCode: "6-4",
    text: "We are monitoring the progress of legislation but have not taken any actions yet",
    additionalInfoType: "none",
  },
  {
    questionCode: "6-4",
    text: "We don´t know what EU Green Claims is",
    additionalInfoType: "none",
  },
  {
    questionCode: "6-4",
    text: "We would like to have guidance on EU Green Claims",
    additionalInfoType: "none",
  },
  {
    questionCode: "6-4",
    text: "This is not relevant for us",
    additionalInfoType: "none",
  },
  {
    questionCode: "6-5",
    text: "We have certificates that cover water impact in Tier 2-4",
    additionalInfoType: "text",
    info: "If other, please describe",
  },
  {
    questionCode: "6-5",
    text: "We use water saving materials and fibers",
    additionalInfoType: "none",
  },
  {
    questionCode: "6-5",
    text: "Our Tier 2-4 production is in countries with sufficint water infrasructure",
    additionalInfoType: "none",
  },
  {
    questionCode: "6-5",
    text: "Other, please describe",
    additionalInfoType: "text",
    info: "Additional information required",
  },
  {
    questionCode: "6-5",
    text: "No",
    additionalInfoType: "none",
  },
  {
    questionCode: "6-5",
    text: "We don´t know",
    additionalInfoType: "none",
  },
  {
    questionCode: "6-6",
    text: "Yes",
    additionalInfoType: "text",
    info: "Your comments / additional information:",
  },
  {
    questionCode: "6-6",
    text: "No",
    additionalInfoType: "none",
  },
  {
    questionCode: "6-6",
    text: "We don't know",
    additionalInfoType: "none",
  },
  {
    questionCode: "6-6",
    text: "This is not relevant to our brand",
    additionalInfoType: "none",
  },
  {
    questionCode: "6-7",
    text: "Yes, carbon footprint",
    additionalInfoType: "url",
    info: "If yes, provide a link or attachment with an example",
  },
  {
    questionCode: "6-7",
    text: "Yes, water footprint",
    additionalInfoType: "url",
    info: "LINK HERE",
  },
  {
    questionCode: "6-7",
    text: "Yes, for land mass",
    additionalInfoType: "text",
    info: "Additional information required",
  },
  {
    questionCode: "6-7",
    text: "Yes, using the Product Environmental Footprint (PEF) method",
    additionalInfoType: "url",
    info: "More information on Product Environmental Footprint (PEF) Guide here: https://ec.europa.eu/environment/eussd/smgp/pdf/EF%20simple%20guide_v7_clen.pdf",
  },
  {
    questionCode: "6-7",
    text: "No",
    additionalInfoType: "none",
  },
  {
    questionCode: "6-7",
    text: "No, but we are interested in finding solutions",
    additionalInfoType: "text",
    info: "THIS INFORMATION WILL BE TREATED AS CONFIDENTIAL.",
  },
  {
    questionCode: "7-1-1",
    text: "Only natural materials",
    additionalInfoType: "text",
    info: "Your comments / additional information:",
  },
  {
    questionCode: "7-1-1",
    text: "Only GOTS or organic cotton",
    additionalInfoType: "none",
  },
  {
    questionCode: "7-1-1",
    text: "Local fibers preferred",
    additionalInfoType: "none",
  },
  {
    questionCode: "7-1-1",
    text: "Recycled fibers preferred",
    additionalInfoType: "none",
  },
  {
    questionCode: "7-1-1",
    text: "No plastic fibers (cellulosic fibers ok)",
    additionalInfoType: "none",
  },
  {
    questionCode: "7-1-1",
    text: "Certified plant based or licenced celluloce fibers preferred",
    additionalInfoType: "none",
  },
  {
    questionCode: "7-1-1",
    text: "Certified animal fibers preferred",
    additionalInfoType: "text",
    info: "If other, please describe:",
  },
  {
    questionCode: "7-1-1",
    text: "Other, please describe",
    additionalInfoType: "text",
    info: "Additional information required",
  },
  {
    questionCode: "7-1-1",
    text: "No, we do not have a material / fiber policy",
    additionalInfoType: "none",
  },
  {
    questionCode: "7-2",
    text: "All products are aligned with the EU REACH regulation",
    additionalInfoType: "text",
    info: "Additional information required",
  },
  {
    questionCode: "7-2",
    text: "The majority (or all) of the materials are certified by OEKO-TEX",
    additionalInfoType: "text",
    info: "If you have any of these chemical policy labels or certificates, describe the use of chemicals, and estimate the amount of production they cover.",
  },
  {
    questionCode: "7-2",
    text: "The majority of the products are certified by Bluesign",
    additionalInfoType: "text",
    info: "Additional information required",
  },
  {
    questionCode: "7-2",
    text: "The majority of the products are aligned with the ZDHC Manufacturing Restricted Substance List",
    additionalInfoType: "none",
  },
  {
    questionCode: "7-2",
    text: "The majority of the products are Cradle to Cradle certified",
    additionalInfoType: "text",
    info: "Additional information required",
  },
  {
    questionCode: "7-2",
    text: "We have our own chemical policy and have eliminated the use of certain suspect chemicals.",
    additionalInfoType: "none",
  },
  {
    questionCode: "7-2",
    text: "We do not have a chemical policy",
    additionalInfoType: "none",
  },
  {
    questionCode: "7-2",
    text: "Not applicable to our brand. Our production does not use harsh chemicals in any wet process, material treatment or dyeing (tier 1-4).",
    additionalInfoType: "none",
  },
  {
    questionCode: "7-3",
    text: "Yes, natural dyes",
    additionalInfoType: "text",
    info: "If yes, please, describe. What type of production methods and techologies.",
  },
  {
    questionCode: "7-3",
    text: "Yes, vegetable-tanned leather",
    additionalInfoType: "none",
  },
  {
    questionCode: "7-3",
    text: "Yes, innovative production technologies to\ndecrease chemical use",
    additionalInfoType: "text",
    info: "Additional information required",
  },
  {
    questionCode: "7-3",
    text: "Other, please describe",
    additionalInfoType: "text",
    info: "Additional information required",
  },
  {
    questionCode: "7-3",
    text: "We do not have a chemical policy",
    additionalInfoType: "none",
  },
  {
    questionCode: "7-3",
    text: "Our products are PFAS-free",
    additionalInfoType: "text",
    info: "THIS INFORMATION WILL BE TREATED AS CONFIDENTIAL.",
  },
  {
    questionCode: "7-4",
    text: "Our entire collection is vegan",
    additionalInfoType: "url",
    info: "Provide link to where this information is stated on your website:",
  },
  {
    questionCode: "7-4",
    text: "Yes, it is not public",
    additionalInfoType: "url",
    info: "LINK HERE",
  },
  {
    questionCode: "7-4",
    text: "Yes, and it is publicly available",
    additionalInfoType: "text",
    info: "Additional information required",
  },
  {
    questionCode: "7-4",
    text: "We don't have animal fibers in our collection",
    additionalInfoType: "none",
  },
  {
    questionCode: "7-4",
    text: "We use only recycled or certified, ethical animal-based materials in our collection.",
    additionalInfoType: "none",
  },
  {
    questionCode: "7-5-1",
    text: "No",
    additionalInfoType: "text",
    info: "NOTE. Farmed fur includes mink, fox, raccoondog, chinchilla, rabbit, goat, dog and cat. It does NOT include lamb, cow, alpaca, chicken feathers or down, geese feathers or down.",
  },
  {
    questionCode: "7-5-1",
    text: "Yes",
    additionalInfoType: "none",
  },
  {
    questionCode: "7-5-1",
    text: "Yes, but we have ethical fur certificate for it",
    additionalInfoType: "text",
    info: "What certificates?",
  },
  {
    questionCode: "7-5-1",
    text: "Yes, it is upcycled or deadstock fur",
    additionalInfoType: "none",
  },
  {
    questionCode: "7-5-1",
    text: "We don´t know",
    additionalInfoType: "none",
  },
  {
    questionCode: "7-5-2",
    text: "No",
    additionalInfoType: "text",
    info: "Where do the feathers / down produced? In which countries?",
  },
  {
    questionCode: "7-5-2",
    text: "Yes",
    additionalInfoType: "none",
  },
  {
    questionCode: "7-5-2",
    text: "Yes, but we have ethical down / fearher certificate for it",
    additionalInfoType: "text",
    info: "What certificates?",
  },
  {
    questionCode: "7-5-2",
    text: "Yes, it is upcycled or recycled fibers",
    additionalInfoType: "none",
  },
  {
    questionCode: "7-5-2",
    text: "We don´t know",
    additionalInfoType: "none",
  },
  {
    questionCode: "7-5-3",
    text: "No",
    additionalInfoType: "text",
    info: "Where is the leather hides treated and leather originated? In which countries?",
  },
  {
    questionCode: "7-5-3",
    text: "Yes",
    additionalInfoType: "none",
  },
  {
    questionCode: "7-5-3",
    text: "Yes, but we have ethical leather certificate for it",
    additionalInfoType: "text",
    info: "What certificates?",
  },
  {
    questionCode: "7-5-3",
    text: "Yes, it is upcycled or recycled leather",
    additionalInfoType: "none",
  },
  {
    questionCode: "7-5-3",
    text: "We don´t know",
    additionalInfoType: "none",
  },
  {
    questionCode: "7-5-4",
    text: "No",
    additionalInfoType: "text",
    info: "Where is the lfibers originated? In which countries?",
  },
  {
    questionCode: "7-5-4",
    text: "Yes",
    additionalInfoType: "none",
  },
  {
    questionCode: "7-5-4",
    text: "Yes, but we have ethical certificate for it",
    additionalInfoType: "text",
    info: "What certificates?",
  },
  {
    questionCode: "7-5-4",
    text: "Yes, it is upcycled or recycled fibers",
    additionalInfoType: "none",
  },
  {
    questionCode: "7-5-4",
    text: "We don´t know",
    additionalInfoType: "none",
  },
  {
    questionCode: "7-6",
    text: "No",
    additionalInfoType: "text",
    info: "Where do the animal based materials and fibers come from in your collection? Which countries?",
  },
  {
    questionCode: "7-6",
    text: "Yes",
    additionalInfoType: "none",
  },
  {
    questionCode: "7-6",
    text: "We know only the fabric/leather origin (tier 2), but\nnot the fiber/hides origin (tier 3-4)",
    additionalInfoType: "none",
  },
  {
    questionCode: "7-6",
    text: "We don't have animal fibers or real leather in our collection",
    additionalInfoType: "none",
  },
  {
    questionCode: "7-6",
    text: "Our entire collection is vegan",
    additionalInfoType: "none",
  },
  {
    questionCode: "7-7",
    text: "Yes, 100% is certified mulesing-free wool",
    additionalInfoType: "text",
    info: "Where is the lambswool produced? In which countries?",
  },
  {
    questionCode: "7-7",
    text: "Yes, over 50% is mulesing-free",
    additionalInfoType: "none",
  },
  {
    questionCode: "7-7",
    text: "Yes, less than 50% is mulesing-free",
    additionalInfoType: "none",
  },
  {
    questionCode: "7-7",
    text: "No, it is not",
    additionalInfoType: "text",
    info: "What certificates does your lambswool have?",
  },
  {
    questionCode: "7-7",
    text: "We don´t know",
    additionalInfoType: "none",
  },
  {
    questionCode: "7-7",
    text: "We don't have any lambs wool our collection",
    additionalInfoType: "none",
  },
  {
    questionCode: "7-7",
    text: "Our entire collection is vegan",
    additionalInfoType: "none",
  },
  {
    questionCode: "7-8",
    text: "Bisphenol A (BPA)",
    additionalInfoType: "none",
  },
  {
    questionCode: "7-8",
    text: "Perchlorate",
    additionalInfoType: "none",
  },
  {
    questionCode: "7-8",
    text: "PFC and PFAS chemicals",
    additionalInfoType: "none",
  },
  {
    questionCode: "7-8",
    text: "Phthalates",
    additionalInfoType: "none",
  },
  {
    questionCode: "7-8",
    text: "Lead",
    additionalInfoType: "text",
    info: "If you choose other, please specify",
  },
  {
    questionCode: "7-8",
    text: "Polybrominated diphenyl ethers (PBDEs)",
    additionalInfoType: "none",
  },
  {
    questionCode: "7-8",
    text: "Silver ion antimicrobial treatmenrs",
    additionalInfoType: "none",
  },
  {
    questionCode: "7-8",
    text: "Other >>>",
    additionalInfoType: "text",
    info: "Additional information required",
  },
  {
    questionCode: "7-8",
    text: "We have OEKO-TEX",
    additionalInfoType: "none",
  },
  {
    questionCode: "7-8",
    text: "All our products are made safely in the EU",
    additionalInfoType: "none",
  },
  {
    questionCode: "7-8",
    text: "We don´t know",
    additionalInfoType: "none",
  },
];
